import Api from '../Api';
import {urlApi} from '../../../config/ApiConfig';

export let estatesWS = {
  createEstate: async function (
    title,
    description,
    rentOrSale,
    status,
    street,
    addressNumber,
    floor,
    neighborhood,
    state,
    country,
    estateType,
    coveredSquareMeters,
    semiUncoveredSquaremeters,
    uncoveredSquareMeters,
    roomsAmount,
    bathroomsAmount,
    bedroomsAmount,
    terrace,
    balcony,
    storage,
    garage,
    frontOrBack,
    antiquity,
    orientation,
    amenites,
    currency,
    price,
    expenseCurrency,
    expenses,
    latitude,
    longitude,
    files,
    videoUrl,
    realEstateId,
  ) {
    console.log(typeof expenses);
    return await Api.post(urlApi.estate.createEstate, {
      title,
      description,
      rentOrSale,
      status,
      street,
      addressNumber,
      floor,
      neighborhood,
      state,
      country,
      estateType,
      coveredSquareMeters,
      semiUncoveredSquaremeters,
      uncoveredSquareMeters,
      roomsAmount,
      bathroomsAmount,
      bedroomsAmount,
      terrace,
      balcony,
      storage,
      garage,
      frontOrBack,
      antiquity,
      orientation,
      amenites,
      currency,
      price,
      expenseCurrency,
      expenses,
      latitude,
      longitude,
      files,
      videoUrl,
      realEstateId,
    });
  },
  getEstatesByUserId: async function (id) {
    return await Api.get(urlApi.estate.getEstateByUser + id);
  },
};
