const NAVIGATOR = {
  START: 'NAVIGATOR_START',
  LOGIN: 'NAVIGATOR_LOGIN',
  LANDING_USER: 'NAVIGATOR_LANDING_USER',
  LANDING_INMOBILIARIA: 'NAVIGATOR_LANDING_INMOBILIARIA',
};
const LOGIN_STACK = {
  LOGIN: 'LOGIN',
  REGISTER: 'REGISTER',
  PASSWORD_RECOVERY: 'PASSWORD_RECOVERY',
  PASSWORD_RECOVERY_CODE: 'PASSWORD_RECOVERY_CODE',
  PASSWORD_RECOVERY_NEW_PASS: 'PASSWORD_RECOVERY_NEW_PASS',
  LOGIN_INMOBILIARIA: 'LOGIN_INMOBILIARIA',
};
const LANDING_USER_STACK = {
  HOME: 'HOME',
  RESERVAS: 'RESERVAS',
  FAVORITOS: 'FAVORITOS',
  PERFIL: 'PERFIL',
};
const LANDING_INMOBILIARIA_STACK = {
  PUBLICACIONES: 'PUBLICACIONES',
  PUBLICAR: 'PUBLICAR',
  PERFIL: 'PERFIL',
};
const FAVORITOS_STACK = {
  ALQUILER: 'ALQUILER',
  VENTA: 'VENTA',
};
const PUBLICACIONES_STACK = {
  ALQUILER: 'ALQUILER',
  VENTA: 'VENTA',
};

export default {
  NAVIGATOR,
  LOGIN_STACK,
  LANDING_USER_STACK,
  LANDING_INMOBILIARIA_STACK,
  FAVORITOS_STACK,
  PUBLICACIONES_STACK,
};
