const NAVIGATOR = {
  START: 'NAVIGATOR_START',
  LOGIN: 'NAVIGATOR_LOGIN',
  LANDING_USER: 'NAVIGATOR_LANDING_USER',
  LANDING_INMOBILIARIA: 'NAVIGATOR_LANDING_INMOBILIARIA',
};
const LOGIN_STACK = {
  LOGIN: 'LOGIN',
  REGISTER: 'REGISTER',
  PASSWORD_RECOVERY: 'PASSWORD_RECOVERY',
  PASSWORD_RECOVERY_CODE: 'PASSWORD_RECOVERY_CODE',
  PASSWORD_RECOVERY_NEW_PASS: 'PASSWORD_RECOVERY_NEW_PASS',
  LOGIN_INMOBILIARIA: 'LOGIN_INMOBILIARIA',
  REGISTER_CODE: 'REGISTER_CODE',
  REGISTER_SUCCESSFUL: 'REGISTER_SUCCESSFUL',
};
const LANDING_USER_STACK = {
  HOME: 'Home',
  RESERVAS: 'Reservas',
  FAVORITOS: 'Favoritos',
  PERFIL: 'Perfil',
};
const LANDING_INMOBILIARIA_STACK = {
  PUBLICACIONES_NAVIGATOR: 'Publicaciones Navigator',
  PUBLICAR: 'Publicar',
  PERFIL_NAVIGATOR: 'Perfil',
};
const FAVORITOS_STACK = {
  ALQUILER: 'ALQUILER',
  VENTA: 'VENTA',
};
const PUBLICACIONES_STACK = {
  ALQUILER: 'ALQUILER',
  VENTA: 'VENTA',
};
const INMOBILIARIA_PERFIL_STACK = {
  PERFIL: 'Perfil Inmobiliaria',
  MIS_DATOS: 'Mis Datos',
  CONSULTAS: 'Consultas',
  CONSULTA_X: 'Consulta X',
  VISITAS_PROGRAMADAS: 'Visitas Programadas',
  VISITA_PROGRAMADA_X: 'Visita Programada X',
  OPINIONES: 'Opiniones',
  PUBLICACION_X: 'Publicacion X Nav',
};
const USER_PERFIL_STACK = {
  PERFIL: 'Perfil usuario',
  MIS_DATOS: 'Mis Datos',
  CONSULTAS: 'Consultas',
  CONSULTA_X: 'Consulta X',
  VISITAS_PROGRAMADAS: 'Visitas Programadas',
  VISITA_PROGRAMADA_X: 'Visita Programada X',
  PUBLICACION_X: 'Publicacion X',
};
const INMOBILIARIA_PUBLICACIONES_STACK = {
  PUBLICACIONES_TOP_TAB: 'Publicaciones',
  PUBLICACION_X: 'Publicacion X Nav',
  EDITAR_PUBLICACION_X: 'Editar publicacion',
};
const USER_FAVORITOS_STACK = {
  FAVORITOS_TOP_TAB: 'Favoritos User',
  PUBLICACION_X: 'Publicacion X Nav',
};
const USER_RESERVAS_STACK = {
  RESERVAS: 'Reservas User',
  PUBLICACION_X: 'Publicacion X',
};
const INMOBILIARIA_PUBLICACION_X_STACK = {
  PUBLICACION_X: 'Publicacion X',
  EDITAR_PUBLICACION_X: 'Editar publicacion',
};
const USER_PUBLICACION_X_STACK = {
  PUBLICACION_X: 'Publicacion X',
  CONTACTO_PROPIEDAD_X: 'Contacto Propiedad X',
  RESERVA_PROPIEDAD_X: 'Reserva Propiedad X',
  CALIFICAR_INMOBILIARIA: 'Calificar Inmobiliaria',
  VER_CALIFICACIONES: 'Ver Calificaciones',
};

export default {
  NAVIGATOR,
  LOGIN_STACK,
  LANDING_USER_STACK,
  LANDING_INMOBILIARIA_STACK,
  FAVORITOS_STACK,
  PUBLICACIONES_STACK,
  INMOBILIARIA_PERFIL_STACK,
  USER_PERFIL_STACK,
  INMOBILIARIA_PUBLICACIONES_STACK,
  USER_FAVORITOS_STACK,
  USER_RESERVAS_STACK,
  INMOBILIARIA_PUBLICACION_X_STACK,
  USER_PUBLICACION_X_STACK,
};
